### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by AlexWayfer** [savetheclocktower/pulsar-ide-ruby-solargraph#1]
Hello.

Thank you for your fork.

Unfortunately, it's stopped working for me with Pulsar Editor version 1.111.0.

Can you please check the package?

**Comment by savetheclocktower** [comment]
Can you set `core.debugLSP` to `true` in your `config.cson`, reload the window, and see if any errors show up in the console?

**Comment by AlexWayfer** [comment]
> Can you set `core.debugLSP` to `true` in your `config.cson`, reload the window, and see if any errors show up in the console?

It was already `true`, I've reloaded the window and now it works…

I guess, there was a mess (conflict) with my packages, I've disabled some of them and had to reload the window.

Sorry and thank you.

**Comment by savetheclocktower** [comment]
No problem. I'd forgotten I made that package; at least now I'll remember to update it when I update the others.
